# Copyright 2020-2024, Embark Studios
# SPDX-License-Identifier: MIT or Apache-2.0

accepted = ["Apache-2.0", "MIT", "BSD-3-Clause", "ISC", "Unicode-3.0", "Zlib", "CDLA-Permissive-2.0"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
]
ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false
filter-noassertion = true
workarounds = ["ring", "chrono", "rustls", "unicode-ident"]

[codespan.clarify]
license = "Apache-2.0"

[[codespan.clarify.git]]
path = "LICENSE"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[codespan-reporting.clarify]
license = "Apache-2.0"

[[codespan-reporting.clarify.git]]
path = "LICENSE"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[failure_derive.clarify]
license = "Apache-2.0 OR MIT"

[[failure_derive.clarify.git]]
path = "LICENSE"
checksum = "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4"

[ring]
accepted = ["OpenSSL"]

[unicode-ident]
accepted = ["Unicode-DFS-2016"]

[webpki-roots]
accepted = ["MPL-2.0"]
