[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]

[advisories]
unmaintained = "workspace"
ignore = []

[bans]
multiple-versions = "deny"
deny = ["openssl-sys", "cmake", "windows"]
skip = [
    { crate = "getrandom@0.2.16", reason = "ring" },
]
skip-tree = [
    # Currently at four fucking versions now
    { crate = "windows-sys", reason = "as always" },
]

[licenses]
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = ["Apache-2.0", "MIT", "BSD-3-Clause", "ISC", "Unicode-3.0"]

exceptions = [
    # ring uses code from multiple libraries but all with permissive licenses
    # https://tldrlegal.com/license/openssl-license-(openssl)
    { allow = ["ISC", "MIT", "OpenSSL"], name = "ring" },

    { allow = ["CDLA-Permissive-2.0"], name = "webpki-roots" },
    { allow = ["Zlib"], name = "foldhash" },
]
